/* Generated By:JJTree: Do not edit this line. ASTArraySize.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

public
class ASTArraySize extends SimpleNode {
  protected String value;

  public ASTArraySize(int id) {
    super(id);
	this.value = "";
  }

  public ASTArraySize(Yal p, int id) {
    super(p, id);
  }

  public void setValues(String value){
	this.value = value;
  }

  @Override
  public String getValue(){ return this.value; }

  @Override
  public String toString() {
	if(this.value != "")
		return "Element [" + this.value + "]";
	else
		return "At";
  }
}
/* JavaCC - OriginalChecksum=2020bd42693cdc8074442d5da9e5778d (do not edit this line) */
