/* Generated By:JJTree: Do not edit this line. ASTArgument.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

public
class ASTArgument extends SimpleNode {
  protected String value;

  public ASTArgument(int id) {
    super(id);
  }

  public ASTArgument(Yal p, int id) {
    super(p, id);
  }

  public void setValues(String value){
    this.value = value;
  }

  @Override
  public String getValue(){ return this.value; }

  @Override
  public String toString() { return  YalTreeConstants.jjtNodeName[id] + " " + this.value; }


}
/* JavaCC - OriginalChecksum=45af526e2c1962f7a052474fcced7705 (do not edit this line) */
