/* Generated By:JJTree: Do not edit this line. ASTAssign.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

public
class ASTAssign extends SimpleNode {
  public ASTAssign(int id) {
    super(id);
  }

  public ASTAssign(Yal p, int id) {
    super(p, id);
  }

  @Override
  public String toString() { return YalTreeConstants.jjtNodeName[id]; }

}
/* JavaCC - OriginalChecksum=191fc68bc31f8d0a019d66c49d6a183b (do not edit this line) */
