/* Generated By:JJTree: Do not edit this line. ASTArgumentList.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

public
class ASTArgumentList extends SimpleNode {
  public ASTArgumentList(int id) {
    super(id);
  }

  public ASTArgumentList(Yal p, int id) {
    super(p, id);
  }

  @Override
  public String toString() { return "Arglist"; }

}
/* JavaCC - OriginalChecksum=158c4811d2c1d36e5a11852f19c82c53 (do not edit this line) */
