/* Generated By:JJTree: Do not edit this line. ASTDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

public
class ASTDeclaration extends SimpleNode {
  protected String assign;
  protected boolean print;

  public ASTDeclaration(int id) {
    super(id);
	this.assign = "";
	this.print = false;
  }

  public ASTDeclaration(Yal p, int id) {
    super(p, id);
  }

  public void setValues(String value){
	if(value != "")
		this.assign = "Assign";
	this.print = true;
  }

  @Override
  public boolean print() { return this.print; }

  @Override
  public String toString() { return this.assign; }

}
/* JavaCC - OriginalChecksum=491103d103f3419980b02c75864a8fdf (do not edit this line) */
