/* Generated By:JJTree: Do not edit this line. ASTExprtest.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

public
class ASTExprtest extends SimpleNode {
  protected String operator;

  public ASTExprtest(int id) {
    super(id);
  }

  public ASTExprtest(Yal p, int id) {
    super(p, id);
  }

  public void setValues(String value){
    this.operator = value;
  }

  @Override
  public String getValue(){ return this.operator; }

  @Override
  public String toString() { return YalTreeConstants.jjtNodeName[id] + " " + this.operator; }

}
/* JavaCC - OriginalChecksum=ffde2350b9d19ac120675162bc625676 (do not edit this line) */
