/* Generated By:JJTree: Do not edit this line. ASTVarlist.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package tree;

public
class ASTVarlist extends SimpleNode {
  public ASTVarlist(int id) {
    super(id);
  }

  public ASTVarlist(Yal p, int id) {
    super(p, id);
  }

  @Override
  public String toString() { return "Arglist"; }

}
/* JavaCC - OriginalChecksum=2ed3dedd15e597d29a7b8c6ee6203b97 (do not edit this line) */
