/* Generated By:JJTree: Do not edit this line. ASTArgumentList.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArgumentList extends SimpleNode {
  public ASTArgumentList(int id) {
    super(id);
  }

  public ASTArgumentList(Yal p, int id) {
    super(p, id);
  }
  
  @Override
  public String toString() { return "Arglist"; }

}
/* JavaCC - OriginalChecksum=8c13f3de9b2d6f4f546051cf4618c8b6 (do not edit this line) */
