/* Generated By:JJTree: Do not edit this line. ASTAssign.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAssign extends SimpleNode {
  public ASTAssign(int id) {
    super(id);
  }

  public ASTAssign(Yal p, int id) {
    super(p, id);
  }

  @Override
  public String toString() { return YalTreeConstants.jjtNodeName[id]; }

}
/* JavaCC - OriginalChecksum=97bead2d9eac64804e582f54a770a4d6 (do not edit this line) */
