/* Generated By:JJTree: Do not edit this line. ASTArraySize.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArraySize extends SimpleNode {
  protected String value;

  public ASTArraySize(int id) {
    super(id);
	this.value = "";
  }

  public ASTArraySize(Yal p, int id) {
    super(p, id);
  }

  public void setValues(String value){
	this.value = value;
  }
  
  @Override
  public String getValue(){ return this.value; }

  @Override
  public String toString() { 
	/*
	return YalTreeConstants.jjtNodeName[id] + " " + this.value;
	*/
	if(this.value != "")
		return "Element [" + this.value + "]";
	else
		return "At";
  }
}
/* JavaCC - OriginalChecksum=074776620eae5525dec8029d81b72b40 (do not edit this line) */
