/* Generated By:JJTree: Do not edit this line. ASTDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDeclaration extends SimpleNode {
  protected int value;

  public ASTDeclaration(int id) {
    super(id);
  }

  public ASTDeclaration(Yal p, int id) {
    super(p, id);
  }

  public void setValues(String value){
    this.value = Integer.parseInt(value);
  }

  @Override
  public String toString() { return YalTreeConstants.jjtNodeName[id] + " " + this.value; }

}
/* JavaCC - OriginalChecksum=c693116af1da8130a4bb532b400ffe46 (do not edit this line) */
