/* Generated By:JJTree: Do not edit this line. ASTDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDeclaration extends SimpleNode {
  protected String assign;
  protected boolean print;

  public ASTDeclaration(int id) {
    super(id);
	this.assign = "";
	this.print = false;
  }

  public ASTDeclaration(Yal p, int id) {
    super(p, id);
  }

  public void setValues(String value){
    this.assign = value;
	this.print = true;
  }
  
  @Override
  public boolean print() { return this.print; }

  @Override
  public String toString() { return this.assign; }

}
/* JavaCC - OriginalChecksum=c693116af1da8130a4bb532b400ffe46 (do not edit this line) */
