/* Generated By:JJTree: Do not edit this line. ASTExprtest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExprtest extends SimpleNode {
  protected String operator;

  public ASTExprtest(int id) {
    super(id);
  }

  public ASTExprtest(Yal p, int id) {
    super(p, id);
  }

  public void setValues(String value){
    this.operator = value;
  }

  @Override
  public String getValue(){ return this.operator; }
  
  @Override
  public String toString() { return YalTreeConstants.jjtNodeName[id] + " " + this.operator; }

}
/* JavaCC - OriginalChecksum=69edcd7f815a99084a8d40f7c580873e (do not edit this line) */
