/* Generated By:JJTree: Do not edit this line. ASTIndex.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIndex extends SimpleNode {
  protected String value;

  public ASTIndex(int id) {
    super(id);
	this.value="";
  }

  public ASTIndex(Yal p, int id) {
    super(p, id);
  }

  public void setValues(String value){
	this.value = value;
  }

  @Override
  public String toString() { 
	/*return YalTreeConstants.jjtNodeName[id] +  "[" + this.value + "]";*/
    return "At " +	this.value;
  }


}
/* JavaCC - OriginalChecksum=1ee29fcde9b33f5ca3341e2621062660 (do not edit this line) */
