/* Generated By:JJTree: Do not edit this line. ASTIntElement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIntElement extends SimpleNode {
  protected String operator;
  protected String value;
  
  public ASTIntElement(int id) {
    super(id);
	this.operator = "";
	this.value = "";
  }

  public ASTIntElement(Yal p, int id) {
    super(p, id);
  }
  
  public void setValues(String operator, String value){
    this.operator = operator;
	this.value = value;
  }
  
  @Override
  public String getValue(){ return this.operator + " " + this.value; }
  
  @Override
  public String toString() { return "Element " + this.operator + this.value; }

}
/* JavaCC - OriginalChecksum=e96e2e1784b160c5913863d6e47fbde0 (do not edit this line) */
