/* Generated By:JJTree: Do not edit this line. ASTModule.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTModule extends SimpleNode {
  protected String name;

  public ASTModule(int id) {
    super(id);
  }

  public ASTModule(Yal p, int id) {
    super(p, id);
  }

  public void setValues(String value){
    this.name = value;
  }
  
  public String getValue(){ return name; }

  @Override
  public String toString() { return YalTreeConstants.jjtNodeName[id] + " " + this.name; }

}
/* JavaCC - OriginalChecksum=1e42ae2d33c6694ad342c7fecc8557c5 (do not edit this line) */
