/* Generated By:JJTree: Do not edit this line. ASTVarlist.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVarlist extends SimpleNode {
  public ASTVarlist(int id) {
    super(id);
  }

  public ASTVarlist(Yal p, int id) {
    super(p, id);
  }
  
  @Override
  public String toString() { return "Arglist"; }

}
/* JavaCC - OriginalChecksum=58f7f5dc44a833d0bb9942b45c463f94 (do not edit this line) */
