/* Generated By:JJTree: Do not edit this line. ASTWhile.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWhile extends SimpleNode {
  public ASTWhile(int id) {
    super(id);
  }

  public ASTWhile(Yal p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ec7a4191a79bfec984d5817098d4dd68 (do not edit this line) */
