/* Generated By:JavaCC: Do not edit this line. YalTreeConstants.java Version 6.0_1 */
public interface YalTreeConstants
{
  public int JJTVOID = 0;
  public int JJTMODULE = 1;
  public int JJTDECLARATION = 2;
  public int JJTFUNCTION = 3;
  public int JJTINTELEMENT = 4;
  public int JJTELEMENT = 5;
  public int JJTASSIGN = 6;
  public int JJTRHS = 7;
  public int JJTARRAYSIZE = 8;
  public int JJTTERM = 9;
  public int JJTEXPRTEST = 10;
  public int JJTWHILE = 11;
  public int JJTIF = 12;
  public int JJTCALL = 13;
  public int JJTARGUMENT = 14;
  public int JJTACCESS = 15;
  public int JJTINDEX = 16;


  public String[] jjtNodeName = {
    "void",
    "Module",
    "Declaration",
    "Function",
    "IntElement",
    "Element",
    "Assign",
    "Rhs",
    "ArraySize",
    "Term",
    "Exprtest",
    "While",
    "If",
    "Call",
    "Argument",
    "Access",
    "Index",
  };
}
/* JavaCC - OriginalChecksum=c361cf6692f9ee2bf80048ec637845e0 (do not edit this line) */
