/* Generated By:JavaCC: Do not edit this line. YalTreeConstants.java Version 6.0_1 */
public interface YalTreeConstants
{
  public int JJTVOID = 0;
  public int JJTMODULE = 1;
  public int JJTDECLARATION = 2;
  public int JJTFUNCTION = 3;
  public int JJTINTELEMENT = 4;
  public int JJTVARLIST = 5;
  public int JJTELEMENT = 6;
  public int JJTASSIGN = 7;
  public int JJTRHS = 8;
  public int JJTARRAYSIZE = 9;
  public int JJTTERM = 10;
  public int JJTEXPRTEST = 11;
  public int JJTWHILE = 12;
  public int JJTIF = 13;
  public int JJTCALL = 14;
  public int JJTARGUMENT = 15;
  public int JJTACCESS = 16;
  public int JJTINDEX = 17;


  public String[] jjtNodeName = {
    "void",
    "Module",
    "Declaration",
    "Function",
    "IntElement",
    "Varlist",
    "Element",
    "Assign",
    "Rhs",
    "ArraySize",
    "Term",
    "Exprtest",
    "While",
    "If",
    "Call",
    "Argument",
    "Access",
    "Index",
  };
}
/* JavaCC - OriginalChecksum=46c5bc0354c6b2fbf3b4ef0754814c32 (do not edit this line) */
